### ISSUE TITLE
[Feat] Tuist로 TCA 기반 Modular Architecture 구현

### ISSUE THREAD

**Issue by L-j-h-c** [Earth-Is-Round/Client-iOS#2]
## 📝  To-do

- [x] Tuist Helper Function
- [x] Excutables ( App / WatchApp )
- [x] XCConfigs
- [x] Feature Modules ( Splash / Main / Setting_
